# Generated by Django 4.0.5 on 2022-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(default=0, verbose_name='Группа'),
        ),
    ]
