# Generated by Django 4.0.5 on 2022-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('authentication', '0006_user_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(related_name='authentication', to='achievements.achievements', verbose_name='Достижения'),
        ),
    ]
