# Generated by Django 4.0.5 on 2022-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_works_student'),
        ('authentication', '0007_remove_user_achievements_user_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='works',
            field=models.ManyToManyField(related_name='authentication', to='works.works', verbose_name='Проекты'),
        ),
    ]
