# Generated by Django 4.0.5 on 2022-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
                ('email', models.EmailField(max_length=255, verbose_name='Email адрес')),
                ('number_of_students', models.IntegerField(default=0, verbose_name='Количество студентов')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
    ]
