# Generated by Django 4.0.5 on 2022-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='works/covers', verbose_name='Обложка')),
                ('file', models.FileField(upload_to='works/files', verbose_name='Файл')),
                ('date', models.DateField(verbose_name='Дата')),
                ('professor', models.ManyToManyField(related_name='works', to='professor.professor', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
