# Generated by Django 4.0.5 on 2022-07-06 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='student',
            field=models.ManyToManyField(related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
