# Generated by Django 4.0.5 on 2022-07-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_works_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='student',
        ),
    ]
